/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppChangesRouteImport } from './routes/_app/changes'
import { Route as AppNewWorkspaceRouteImport } from './routes/_app/new-workspace'
import { Route as AppTidyRouteImport } from './routes/_app/tidy'
import { Route as AppWorkspacesWorkspaceIdIndexRouteImport } from './routes/_app/workspaces.$workspaceId.index'
import { Route as AppWorkspacesWorkspaceIdSessionsSessionIdRouteImport } from './routes/_app/workspaces.$workspaceId.sessions.$sessionId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppChangesRoute = AppChangesRouteImport.update({
  id: '/changes',
  path: '/changes',
  getParentRoute: () => AppRoute,
} as any)
const AppNewWorkspaceRoute = AppNewWorkspaceRouteImport.update({
  id: '/new-workspace',
  path: '/new-workspace',
  getParentRoute: () => AppRoute,
} as any)
const AppTidyRoute = AppTidyRouteImport.update({
  id: '/tidy',
  path: '/tidy',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspacesWorkspaceIdIndexRoute =
  AppWorkspacesWorkspaceIdIndexRouteImport.update({
    id: '/workspaces/$workspaceId/',
    path: '/workspaces/$workspaceId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppWorkspacesWorkspaceIdSessionsSessionIdRoute =
  AppWorkspacesWorkspaceIdSessionsSessionIdRouteImport.update({
    id: '/workspaces/$workspaceId/sessions/$sessionId',
    path: '/workspaces/$workspaceId/sessions/$sessionId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/changes': typeof AppChangesRoute
  '/new-workspace': typeof AppNewWorkspaceRoute
  '/tidy': typeof AppTidyRoute
  '/workspaces/$workspaceId/': typeof AppWorkspacesWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/sessions/$sessionId': typeof AppWorkspacesWorkspaceIdSessionsSessionIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/changes': typeof AppChangesRoute
  '/new-workspace': typeof AppNewWorkspaceRoute
  '/tidy': typeof AppTidyRoute
  '/': typeof AppIndexRoute
  '/workspaces/$workspaceId': typeof AppWorkspacesWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/sessions/$sessionId': typeof AppWorkspacesWorkspaceIdSessionsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_app/changes': typeof AppChangesRoute
  '/_app/new-workspace': typeof AppNewWorkspaceRoute
  '/_app/tidy': typeof AppTidyRoute
  '/_app/': typeof AppIndexRoute
  '/_app/workspaces/$workspaceId/': typeof AppWorkspacesWorkspaceIdIndexRoute
  '/_app/workspaces/$workspaceId/sessions/$sessionId': typeof AppWorkspacesWorkspaceIdSessionsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/changes'
    | '/new-workspace'
    | '/tidy'
    | '/workspaces/$workspaceId/'
    | '/workspaces/$workspaceId/sessions/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/changes'
    | '/new-workspace'
    | '/tidy'
    | '/'
    | '/workspaces/$workspaceId'
    | '/workspaces/$workspaceId/sessions/$sessionId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/setup'
    | '/_app/changes'
    | '/_app/new-workspace'
    | '/_app/tidy'
    | '/_app/'
    | '/_app/workspaces/$workspaceId/'
    | '/_app/workspaces/$workspaceId/sessions/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/changes': {
      id: '/_app/changes'
      path: '/changes'
      fullPath: '/changes'
      preLoaderRoute: typeof AppChangesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/new-workspace': {
      id: '/_app/new-workspace'
      path: '/new-workspace'
      fullPath: '/new-workspace'
      preLoaderRoute: typeof AppNewWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tidy': {
      id: '/_app/tidy'
      path: '/tidy'
      fullPath: '/tidy'
      preLoaderRoute: typeof AppTidyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspaces/$workspaceId/': {
      id: '/_app/workspaces/$workspaceId/'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId/'
      preLoaderRoute: typeof AppWorkspacesWorkspaceIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspaces/$workspaceId/sessions/$sessionId': {
      id: '/_app/workspaces/$workspaceId/sessions/$sessionId'
      path: '/workspaces/$workspaceId/sessions/$sessionId'
      fullPath: '/workspaces/$workspaceId/sessions/$sessionId'
      preLoaderRoute: typeof AppWorkspacesWorkspaceIdSessionsSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppChangesRoute: typeof AppChangesRoute
  AppNewWorkspaceRoute: typeof AppNewWorkspaceRoute
  AppTidyRoute: typeof AppTidyRoute
  AppIndexRoute: typeof AppIndexRoute
  AppWorkspacesWorkspaceIdIndexRoute: typeof AppWorkspacesWorkspaceIdIndexRoute
  AppWorkspacesWorkspaceIdSessionsSessionIdRoute: typeof AppWorkspacesWorkspaceIdSessionsSessionIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChangesRoute: AppChangesRoute,
  AppNewWorkspaceRoute: AppNewWorkspaceRoute,
  AppTidyRoute: AppTidyRoute,
  AppIndexRoute: AppIndexRoute,
  AppWorkspacesWorkspaceIdIndexRoute: AppWorkspacesWorkspaceIdIndexRoute,
  AppWorkspacesWorkspaceIdSessionsSessionIdRoute:
    AppWorkspacesWorkspaceIdSessionsSessionIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
